services:

  # ============================================
  # üí∞ WALLET SERVICE
  # ============================================

  wallet-service:
    build: .
    container_name: wallet-service
    depends_on:
      wallet-postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GATEWAY_SECRET=${GATEWAY_SECRET}
      - SERVICE_SECRET=${SERVICE_SECRET}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092 # Kafka broker address
      - KAFKA_TOPIC_ORDER_EXECUTED=order.executed # executed orders topic
    restart: always
    networks:
      - brokerx-network

  wallet-postgres:
    image: postgres:17
    container_name: wallet-postgres
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    expose:
      - "5432"
    volumes:
      - wallet_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - brokerx-network

  wallet-redis:
    image: redis:7.4
    container_name: wallet-redis
    restart: always
    expose:
      - "6379"
    command: [
      "redis-server",
      "--save", "",
      "--appendonly", "no"
    ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - brokerx-network

# ============================================
# üåê NETWORKS
# ============================================

networks:
  brokerx-network:
    external: true
    name: brokerx-network

# ============================================
# üíæ VOLUMES
# ============================================

volumes:
  wallet_postgres_data:
    name: wallet_postgres_data